### ISSUE TITLE
can't find module 'modules/es5'

### ISSUE THREAD

**Issue by Lambert-S** [reactjs/react-redux#340]
Error: Cannot find module './modules/es5'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/lambert/Dev/React-Native/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-polyfill/node_modules/core-js/shim.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by markerikson** [comment]
Sorry, that really doesn't look like a React-Redux problem.  The stack trace makes it look like it probably has more to do with the "core-js" library that Babel uses to help implement ES6 behavior.

Also, just dumping a stack trace, with no explanation of what you're doing or what you might have looked at to try to fix the problem, is not a good way to try to get help.
