### ISSUE TITLE
Issue with calls

### ISSUE THREAD

**Issue by krainboltgreene** [reactjs/react-redux#635]
So I had a rather frustrating evening debugging an issue. I'm using `transform-decorators-legacy` and I went to use `redux-react`.

Here's the error I received:

```
 Invariant Violation: You must pass a component to the function returned by connect. Instead received [object Object]
     at invariant (/usr/lib/www/node_modules/invariant/invariant.js:42:15)
     at wrapWithConnect (/usr/lib/www/node_modules/react-redux/lib/components/connectAdvanced.js:80:29)
     at /usr/lib/www/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16
     at measureLifeCyclePerf (/usr/lib/www/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/usr/lib/www/node_modules/react-dom/lib/ReactCompositeComponent.js:305:14)
     at ReactCompositeComponentWrapper._constructComponent (/usr/lib/www/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
     at ReactCompositeComponentWrapper.mountComponent (/usr/lib/www/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
     at Object.mountComponent (/usr/lib/www/node_modules/react-dom/lib/ReactReconciler.js:46:35)
     at ReactDOMComponent.mountChildren (/usr/lib/www/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
     at ReactDOMComponent._createContentMarkup (/usr/lib/www/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
```

This told me none of what I actually needed to know:

  1. Which component
  2. What the object was
  3. What this likely related to

I edited the source code to get some more useful errors, changing:

``` js
    (0, _invariant2.default)(typeof WrappedComponent == 'function', 'You must pass a component to the function returned by ' + ('connect. Instead received ' + WrappedComponent));
```

to:

``` js
    (0, _invariant2.default)(typeof WrappedComponent == 'function', 'You must pass a component to the function returned by ' + ('connect. Instead received ' + JSON.stringify(WrappedComponent)));
```

Which changed the error message to:

```
Invariant Violation: You must pass a component to the function returned by connect. Instead received {"kind":"primary","href":"/sign-up","children":"Join us"}
```

This was way more useful, but still I had no idea what was going on so I found that text (The `"children"` field):

``` javascript
<Anchor kind="primary" href="/sign-up">
  Join us
</Anchor>
```

Nothing strange here, so I looked at the `Anchor` component:

``` javascript
import React, {PureComponent, PropTypes} from "react"
import {connect} from "react-redux"

@connect
export default class Anchor extends PureComponent {
  {{...}}
  render () {
    {{...}}

    return <a {{...}}>
      {children}
    </a>
  }
}
```

Turns out you can't use `@connect` bare like that, you *have* to provide it some function that results in the props object.

I'm just making this issue as a helpful guide for anyone else searching for this very error message.

**Comment by markerikson** [comment]
For what it's worth, the Redux team discourages the use of `connect` as a decorator for several reasons.  This kind of issue is one of them.  There's no real benefit to doing so, and as far as I know we don't really "support" that approach.

**Comment by krainboltgreene** [comment]
Yeah and there's not much react redux can really do here, which is why I
auto closed.
