### ISSUE TITLE
SyntaxError: Unexpected token import, import baseGetTag from './_baseGetTag.js';

### ISSUE THREAD

**Issue by wzup** [reactjs/react-redux#839]
`react-redux` throws this when SSR:

```
C:\Users\app\dist\js\server.js:18247
import baseGetTag from './_baseGetTag.js';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\app\routes\index.js:10:16)
```

Here is my set up that `react-redux` fails to understand:

`provider.js` file. Both lines (`import` or `require`) throws. This file is compiled by Webpack. So Node.js should understand it all right.
```
'use strict';

import { Provider } from 'react-redux';
const Provider = require('react-redux').Provider;

module.exports = Provider;
```

Node.js `route.js` file. The error is observed in this `require` line.
```
let provider = require('../dist/provider');
```

**Comment by wzup** [comment]
False alarm. My bad.

My Webpack config had this line which instructed webpack to ignore and not to compile `lodash`. Didn't delete the line after poking around with webpack.


```
    module: {
        noParse: function(content) {
            return /jquery|lodash/.test(content); // <= Just delete that lodash from here
        },
```

**Comment by GaneshP25** [comment]
same issue i am also facing
when using d3-speedometer
